export const CONFIG = {
  AVIATIONSTACK_API_KEY: "",
  AVIATIONSTACK_BASE_URL: "https://api.aviationstack.com/v1/flights",
  OPENWEATHER_API_KEY: "",
  OPENWEATHER_URL:
    "https://api.openweathermap.org/data/2.5/weather?units=metric&lang=pl&q=",
  AIRLINE_ICON_BASE_URL:
    "https://canvas.samsungvx.com/organizations/23599CF5-F41D-471A-97F1-6F3872F2A44C/partners/D3B51B78-81FA-4A0F-834A-2AE311ECCDD4/widget/icons/",
  WEATHER_CACHE_TTL: 3600000,
  DATA_REFRESH_INTERVAL: 60000,
  WEATHER_REFRESH_INTERVAL: 600000,
};

export const IATA_TO_CITY_MAPPING = {
  WAW: "WARSAW",
  BCN: "BARCELONA",
  BER: "BERLIN",
  KE: "NAIROBI",
  DEL: "DELHI",
};

export const IATA_CITY_MAPPING = [
  { iata: "WAW", city: "Warsaw" },
  { iata: "JFK", city: "New York" },
  { iata: "EWR", city: "Newark" },
  { iata: "ORD", city: "Chicago" },
  { iata: "LAX", city: "Los Angeles" },
  { iata: "MIA", city: "Miami" },
  { iata: "SFO", city: "San Francisco" },
  { iata: "YYZ", city: "Toronto" },
  { iata: "YUL", city: "Montreal" },
  { iata: "LHR", city: "London Heathrow" },
  { iata: "LGW", city: "London Gatwick" },
  { iata: "LTN", city: "London Luton" },
  { iata: "STN", city: "London Stansted" },
  { iata: "DUB", city: "Dublin" },
  { iata: "MAN", city: "Manchester" },
  { iata: "EDI", city: "Edinburgh" },
  { iata: "AMS", city: "Amsterdam" },
  { iata: "CDG", city: "Paris Charles de Gaulle" },
  { iata: "ORY", city: "Paris Orly" },
  { iata: "BRU", city: "Brussels" },
  { iata: "FRA", city: "Frankfurt" },
  { iata: "MUC", city: "Munich" },
  { iata: "DUS", city: "Düsseldorf" },
  { iata: "HAM", city: "Hamburg" },
  { iata: "CGN", city: "Cologne" },
  { iata: "STR", city: "Stuttgart" },
  { iata: "HAJ", city: "Hanover" },
  { iata: "NUE", city: "Nuremberg" },
  { iata: "BER", city: "Berlin" },
  { iata: "ZRH", city: "Zurich" },
  { iata: "GVA", city: "Geneva" },
  { iata: "BSL", city: "Basel" },
  { iata: "VIE", city: "Vienna" },
  { iata: "BUD", city: "Budapest" },
  { iata: "PRG", city: "Prague" },
  { iata: "CPH", city: "Copenhagen" },
  { iata: "ARN", city: "Stockholm" },
  { iata: "NYO", city: "Stockholm Skavsta" },
  { iata: "GOT", city: "Gothenburg" },
  { iata: "OSL", city: "Oslo" },
  { iata: "TRF", city: "Oslo Torp" },
  { iata: "HEL", city: "Helsinki" },
  { iata: "RIX", city: "Riga" },
  { iata: "TLL", city: "Tallinn" },
  { iata: "VNO", city: "Vilnius" },
  { iata: "ZAG", city: "Zagreb" },
  { iata: "LJU", city: "Ljubljana" },
  { iata: "SOF", city: "Sofia" },
  { iata: "BOJ", city: "Burgas" },
  { iata: "VAR", city: "Varna" },
  { iata: "CLJ", city: "Cluj-Napoca" },
  { iata: "OTP", city: "Bucharest" },
  { iata: "SKG", city: "Thessaloniki" },
  { iata: "ATH", city: "Athens" },
  { iata: "CHQ", city: "Chania" },
  { iata: "HER", city: "Heraklion" },
  { iata: "RHO", city: "Rhodes" },
  { iata: "CFU", city: "Corfu" },
  { iata: "ZTH", city: "Zakynthos" },
  { iata: "JMK", city: "Mykonos" },
  { iata: "JTR", city: "Santorini" },
  { iata: "LCA", city: "Larnaca" },
  { iata: "PFO", city: "Paphos" },
  { iata: "IST", city: "Istanbul" },
  { iata: "SAW", city: "Istanbul Sabiha" },
  { iata: "AYT", city: "Antalya" },
  { iata: "DLM", city: "Dalaman" },
  { iata: "ADB", city: "Izmir" },
  { iata: "ESB", city: "Ankara" },
  { iata: "TLV", city: "Tel Aviv" },
  { iata: "CAI", city: "Cairo" },
  { iata: "HRG", city: "Hurghada" },
  { iata: "SSH", city: "Sharm El Sheikh" },
  { iata: "DXB", city: "Dubai" },
  { iata: "DWC", city: "Dubai Al Maktoum" },
  { iata: "AUH", city: "Abu Dhabi" },
  { iata: "DOH", city: "Doha" },
  { iata: "AMM", city: "Amman" },
  { iata: "DEL", city: "Delhi" },
  { iata: "BOM", city: "Mumbai" },
  { iata: "ICN", city: "Seoul" },
  { iata: "HND", city: "Tokyo Haneda" },
  { iata: "NRT", city: "Tokyo Narita" },
  { iata: "PEK", city: "Beijing" },
  { iata: "SIN", city: "Singapore" },
  { iata: "BKK", city: "Bangkok" },
  { iata: "CUN", city: "Cancún" },
  { iata: "MEX", city: "Mexico City" },
  { iata: "AGP", city: "Malaga" },
  { iata: "PMI", city: "Palma de Mallorca" },
  { iata: "BCN", city: "Barcelona" },
  { iata: "REU", city: "Reus" },
  { iata: "MAD", city: "Madrid" },
  { iata: "LIS", city: "Lisbon" },
  { iata: "FNC", city: "Funchal" },
  { iata: "ALC", city: "Alicante" },
  { iata: "TFS", city: "Tenerife South" },
  { iata: "LPA", city: "Gran Canaria" },
  { iata: "IBZ", city: "Ibiza" },
  { iata: "CTA", city: "Catania" },
  { iata: "NAP", city: "Naples" },
  { iata: "FCO", city: "Rome Fiumicino" },
  { iata: "CIA", city: "Rome Ciampino" },
  { iata: "BRI", city: "Bari" },
  { iata: "BLQ", city: "Bologna" },
  { iata: "VCE", city: "Venice" },
  { iata: "MXP", city: "Milan Malpensa" },
  { iata: "LIN", city: "Milan Linate" },
  { iata: "MLA", city: "Malta" },
  { iata: "TRN", city: "Turin" },
  { iata: "NCE", city: "Nice" },
  { iata: "SVO", city: "Moscow Sheremetyevo" },
  { iata: "GDN", city: "Gdańsk" },
  { iata: "KRK", city: "Kraków" },
  { iata: "KTW", city: "Katowice" },
  { iata: "POZ", city: "Poznań" },
  { iata: "LCJ", city: "Łódź" },
  { iata: "LUZ", city: "Lublin" },
  { iata: "KEF", city: "Keflavík" },
];

